export const BOTTOM_TABS_ID = 'BOTTOM_TABS_ID';
export const AUTH_STACK_ID = 'AUTH_STACK_ID';
export const HOME_STACK_ID = 'HOME_STACK_ID';
export const SETTINGS_STACK_ID = 'SETTINGS_STACK_ID';
export const PROFILE_STACK_ID = 'PROFILE_STACK_ID';